CREATE SCHEMA EXAMPLE2;

CREATE TABLE EXAMPLE2.keytest (
 name VARCHAR(30) NOT NULL,
 bar INTEGER NOT NULL,
 foo INTEGER NOT NULL,
 attr VARCHAR(30) NOT NULL,
 baz INTEGER NOT NULL,

 PRIMARY KEY(foo, name, bar)
);
