CREATE TABLE ARBITRARY0.a
  ( a0 BIGINT NOT NULL
  , a1 BIGINT NOT NULL
  , a2 BIGINT NOT NULL
  );

CREATE TABLE ARBITRARY0.b
  ( b0 BIGINT NOT NULL
  , b1 BIGINT NOT NULL
  , b2 BIGINT NOT NULL
  );
