CREATE DATABASE TEST DEFAULT CHARACTER SET UTF8;
CREATE TABLE TEST.user (id BIGINT PRIMARY KEY, name VARCHAR(32) NOT NULL, memo TEXT, created_at DATE NOT NULL);
INSERT INTO TEST.user (id, name, created_at) VALUES (1, 'krdlab', NOW());
