CREATE SCHEMA EXAMPLE4;

CREATE TABLE EXAMPLE4.one (
 seq SERIAL NOT NULL,
 data INTEGER NOT NULL,
 PRIMARY KEY (seq)
);

CREATE TABLE EXAMPLE4.stock_goods (
 seq  INTEGER NOT NULL,
 name VARCHAR(30) NOT NULL,
 unit INTEGER NOT NULL,
 amount INTEGER NOT NULL,

 PRIMARY KEY(seq)
);
